### ISSUE TITLE
Plugin problems

### ISSUE THREAD

**Issue by pchlebda** [Mashape/kong-oauth2-hello-world#7] opened 2017-09-08 12:35 UTC
I run my kong on docker.
After following instructions on https://github.com/Mashape/kong-oauth2-hello-world
I still get {"message":"no API found with those values"} .
The logs in /usr/local/kong/logs don't give much information either.
Could you please advise ?

**Comment by bgouz** [comment] 2017-09-12 17:42
The problems is likely not with the plugin, but with how yiu configured your APIs. Should be easy to troubleshoot  (please supply the /apis admin endpoint)

**Comment by progamer71** [comment] 2017-12-18 04:17
@pchlebda you probably have the same problem as me.
Please look at my closed ticket #10.

**Comment by Tieske** [comment] 2018-11-21 14:24
duplicate of #10. Readme was updated.

**Closed as completed by Tieske** 2018-11-21 14:24 UTC
